name: Pull Request Validate

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - develop
      - master

env:
    REVIEWERS: bdoooh

jobs:
  onOpenedPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Add Pull Request Reviewers
        uses: sakhnovict/add-reviewers-action@1.0.0
        with:
          reviewers: ${{ env.REVIEWERS }}
          token: ${{ secrets.ACTIONS_KEY }}
